spring:
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  datasource:
    hikari:
      jdbc-url: ${JDBC_URL}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
